apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-client
  labels:
    app: kafka-client
spec:
  selector:
    matchLabels:
      app: kafka-client
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-client
    spec:
      containers:
        - image: latonaio/kafka-consumer:latest
          name: kafka-client
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_SERVER
              value: "kafka-0.kafka-service.default.svc.cluster.local:9092,kafka-1.kafka-service.default.svc.cluster.local:9092,kafka-2.kafka-service.default.svc.cluster.local:9092"
            - name: KAFKA_TOPIC
              value: "template-matching"
            - name: KAFKA_PARTITION
              value: "0"
          resources:
            limits:
              cpu: "0.5"
              memory: "100Mi"
            requests:
              cpu: "0.25"
              memory: "50Mi"

